---
abstract: 'require a minimum version for your dependencies'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Cwd: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Path: '2.07'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Test::Builder::Tester: '0'
  Test::Fatal: '0'
  Test::MockModule: '0.14'
  Test::More: '0.88'
  constant: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-RequiredMinimumDependencyVersion
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Carp: '0'
  Perl::PrereqScanner: '0'
  Test::Builder: '0'
  Test::XTFiles: '0'
  perl: '5.006'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion/issues
  homepage: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion
  repository: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion.git
version: '0.003'
