---
abstract: 'require a minimum version for your dependencies'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Test::Builder::Tester: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  Test::TempDir::Tiny: '0'
  constant: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-RequiredMinimumDependencyVersion
no_index:
  directory:
    - corpus
    - t
    - xt
provides:
  Test::RequiredMinimumDependencyVersion:
    file: lib/Test/RequiredMinimumDependencyVersion.pm
    version: '0.003'
requires:
  Carp: '0'
  Perl::PrereqScanner: '0'
  Test::Builder: '0'
  Test::XTFiles: '0'
  perl: '5.006'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion/issues
  homepage: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion
  repository: https://github.com/skirmess/Test-RequiredMinimumDependencyVersion.git
version: '0.003'
x_spdx_expression: BSD-2-Clause-FreeBSD
